// This is autogenerated file , edit if only you are sure

export * from "./authentication.interface";
export * from "./crud.interface";
export * from "./file.interface";
export * from "./followers.interface";
export * from "./mail.interface";
export * from "./pagination.interface";
export * from "./validator.interface";
