queue_rules:
  - name: renovate
    conditions:
      - author=dependabot[bot]
      - status-success=build-and-publish

pull_request_rules:
- name: merge pull requests from renovate bot if CI passes
  conditions:
    - author=renovate[bot]
    - status-success=build
  actions:
    queue:
      name: renovate