# hoisting behavior
hoist: true
shamefullyHoist: true

# dependency behavior
dedupeDirectDeps: true
legacyPeerDeps: true

ignoreWorkspaceRootCheck: true
shellEmulator: true

trustPolicy: no-downgrade
