allowBuilds:
  "@firebase/util": true
  "@nestjs/core": true
  "@scarf/scarf": true
  "@swc/core": true
  argon2: true
  cpu-features: false
  protobufjs: false
  puppeteer: true
  sharp: true
  ssh2: false
  unrs-resolver: false

blockExoticSubdeps: false
minimumReleaseAge: 0

# dependency behavior
dedupeDirectDeps: true

# hoisting behavior
hoist: true
shamefullyHoist: true

ignoreWorkspaceRootCheck: true
onlyBuiltDependencies:
  - "@firebase/util"
  - "@nestjs/core"
  - "@scarf/scarf"
  - "@swc/core"
  - argon2
  - core-js
  - cpu-features
  - nestjs-pino
  - protobufjs
  - sharp
  - ssh2
  - unrs-resolver
