onlyBuiltDependencies:
  - '@firebase/util'
  - '@nestjs/core'
  - '@scarf/scarf'
  - '@swc/core'
  - argon2
  - core-js
  - cpu-features
  - nestjs-pino
  - protobufjs
  - sharp
  - ssh2
  - unrs-resolver
