// This is autogenerated file , edit if only you are sure

export * from "./casl.module";
export * from "./casl-ability.factory";
export * from "./generic.policy";
export * from "./policies.decorator";
export * from "./policies.guard";
export * from "./policy.interface";
