// Part of the public API: never rename or repurpose a value.
export const ERROR_CODES = {
  AUTH_TOKEN_MISSING: "AUTH_TOKEN_MISSING",
  CURSOR_INVALID_DATE: "CURSOR_INVALID_DATE",
  CURSOR_INVALID_NUMBER: "CURSOR_INVALID_NUMBER",
  SERVICE_UNDER_MAINTENANCE: "SERVICE_UNDER_MAINTENANCE",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",
  TOKEN_INVALID: "TOKEN_INVALID",
  TOKEN_MALFORMED: "TOKEN_MALFORMED",
  USER_NOT_FOUND: "USER_NOT_FOUND",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
