// This is autogenerated file , edit if only you are sure

export * from "./activity-log.entity";
export * from "./category.entity";
export * from "./comment.entity";
export * from "./otp-log.entity";
export * from "./post.entity";
export * from "./protocol.entity";
export * from "./refresh-token.entity";
export * from "./tag.entity";
export * from "./user.entity";
