import Joi from "joi";

export const validationSchema = Joi.object({
	NODE_ENV: Joi.string().valid("dev", "prod", "stage", "test").required(),
	APP_PORT: Joi.number().required(),
	APP_PREFIX: Joi.string().required(),
	SWAGGER_USER: Joi.string().required(),
	SWAGGER_PASSWORD: Joi.string().required(),
	DB_HOST: Joi.string().required(),
	DB_PORT: Joi.number().required(),
	DB_USERNAME: Joi.string().required(),
	DB_PASSWORD: Joi.string().required(),
	DB_DATABASE: Joi.string().required(),
	JWT_SECRET: Joi.string().required().min(8),
	JWT_REFRESH_EXPIRY: Joi.number().required(),
	JWT_ACCESS_EXPIRY: Joi.string().required(),
	MAIL_USERNAME: Joi.string().required(),
	MAIL_PASSWORD: Joi.string().required(),
	MAIL_HOST: Joi.string().required(),
	MAIL_PORT: Joi.number().required(),
	MAIL_PREVIEW_EMAIL: Joi.boolean().default(false).required(),
	MAIL_TEMPLATE_DIR: Joi.string().required(),
	MAIL_SENDER_EMAIL: Joi.string().required(),
	MAIL_SERVER: Joi.string().required(),
	REDIS_URI: Joi.string().required(),
	REDIS_TTL: Joi.number().required(),
	CLOUDINARY_CLOUD_NAME: Joi.string().required(),
	CLOUDINARY_API_KEY: Joi.string().required(),
	CLOUDINARY_API_SECRET: Joi.string().required(),
	RABBITMQ_URI: Joi.string().required(),
	RABBITMQ_EXCHANGE: Joi.string().required(),
	SENTRY_DSN: Joi.string().required(),
	GOOGLE_CLIENT_ID: Joi.string().required(),
	GOOGLE_CLIENT_SECRET: Joi.string().required(),
	GOOGLE_CALLBACK_URL: Joi.string().required(),
	FACEBOOK_CLIENT_ID: Joi.string().required(),
	FACEBOOK_CLIENT_SECRET: Joi.string().required(),
	FACEBOOK_CALLBACK_URL: Joi.string().required(),
});
