
on:
  schedule:
    # Runs every hour
    - cron: '0 * * * *'
  workflow_dispatch:
  
name: Renovate
jobs:
  renovate:
    name: Renovate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Run Renovate
        uses: docker://renovate/renovate:slim
        env:
          RENOVATE_REPOSITORIES: rubiin/ultimate-nest
          RENOVATE_TOKEN: ${{ secrets.TOKEN_GITHUB }}
